### ISSUE TITLE
What is the difference between URI and URL?

### ISSUE THREAD

**Issue by cvhorie** [jronallo/iiif-workshop-new#15]
http://ronallo.com/iiif-workshop-new/image-api/uri-parameters.html
The constructed URI appears identical to the URL used to display the image.

**Comment by jronallo** [comment]
Yes, in this context they're the same and URI and URL refer to the same thing. A URL is a type of URI. I hope that helps clarify.

**Comment by cvhorie** [comment]
As a novice, I start off confused. I spent 15 minutes trying to work out the difference between URI and URL, and failed. Was it just another typo (I had never heard of a URI), what meaning am I not understanding, is the difference important, how?
Now I am assured that a URI is a real thing, the best advice I have seen is: "I personally use “URL” in most cases because it’s least likely to cause confusion,"  I suggest that you apply Occam's razor.
